[[redirects]]
  from = "/scale-ready-os"
  to = "/scale-ready-os-waitlist-page.html"
  status = 200
  force = true

[[redirects]]
  from = "/terms"
  to = "/Terms.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/Privacy.html"
  status = 200
